name: Update summary cards

on:
  schedule:
    - cron: "0 0 * * *"   # обновлять раз в день
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: tanat0
          BRANCH_NAME: main
          AUTO_PUSH: false   # отключаем автопуш
          # Используем dracula тему для более красивого отображения
          # GITHUB_TOKEN автоматически предоставляет доступ к приватным репо

      - name: Commit summary cards
        uses: EndBug/add-and-commit@v9
        with:
          message: "update summary cards"
          add: "profile-summary-card-output"

